name: Angular CI

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  TEST_SCRIPT: ${{ ng test --sourceMap=false --browsers=ChromeHeadless --watch=false }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 10.x ]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Cache Node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run env.TEST_SCRIPT
